/**
 * FreightFlow AI — Mock Provider (Dev / Offline / CI)
 * 
 * Returns synthetic, deterministic AI responses for local development,
 * demo environments, automated testing, and offline/no-API-key scenarios.
 */

/**
 * Generate a mock response based on prompt content analysis.
 * @param {string} systemPrompt - System-level instructions (ignored in mock)
 * @param {string} userPrompt - User query with context
 * @returns {Promise<string>} Synthetic AI response
 */
export async function generateResponse(systemPrompt, userPrompt) {
  // Simulate network latency
  await new Promise(resolve => setTimeout(resolve, 300 + Math.random() * 400));

  const lower = userPrompt.toLowerCase();

  // Account Summary pattern
  if (lower.includes('account summary') || lower.includes('summarize') || lower.includes('account context')) {
    // Try to extract account name from context
    const nameMatch = userPrompt.match(/"name":\s*"([^"]+)"/);
    const accountName = nameMatch ? nameMatch[1] : 'this account';
    return `## ${accountName} — Executive Summary\n\n` +
      `**${accountName}** is a valued logistics customer with an active operational relationship.\n\n` +
      `### Key Metrics\n` +
      `- **Revenue:** Based on current invoices and pipeline activity\n` +
      `- **Shipment Volume:** Active shipments in progress\n` +
      `- **Relationship Health:** Strong — regular engagement observed\n\n` +
      `### Risk Assessment\n` +
      `- **Overall Risk:** Low\n` +
      `- No outstanding customs holds or delayed shipments detected\n\n` +
      `### Recommended Actions\n` +
      `1. Schedule quarterly business review\n` +
      `2. Review upcoming shipment pipeline capacity\n` +
      `3. Verify all trade compliance documents are current\n\n` +
      `*Generated by FreightFlow AI (Mock Provider — Development Mode)*`;
  }

  // Search/command patterns
  if (lower.includes('show') || lower.includes('find') || lower.includes('search') || lower.includes('list')) {
    return `I found relevant records matching your query. Here is a summary of the results based on your current CRM data.\n\n` +
      `Please review the records displayed and let me know if you need more details on any specific entity.\n\n` +
      `*Generated by FreightFlow AI (Mock Provider — Development Mode)*`;
  }

  // Shipment patterns
  if (lower.includes('shipment') || lower.includes('delay') || lower.includes('tracking')) {
    return `### Shipment Analysis\n\n` +
      `Based on the current operational data, here is the shipment status overview:\n\n` +
      `- Active shipments are progressing within normal parameters\n` +
      `- No critical delays detected at this time\n` +
      `- Customs clearances are proceeding as expected\n\n` +
      `**Recommended:** Monitor any shipments approaching their estimated delivery window.\n\n` +
      `*Generated by FreightFlow AI (Mock Provider — Development Mode)*`;
  }

  // Default fallback
  return `I understand your query: "${userPrompt.substring(0, 100)}..."\n\n` +
    `Based on your FreightFlow CRM data, I can help you with:\n` +
    `- **Account summaries** and relationship health\n` +
    `- **Shipment tracking** and operational status\n` +
    `- **Lead and opportunity** insights\n` +
    `- **Revenue and pipeline** analytics\n\n` +
    `Could you please be more specific about what you'd like to know?\n\n` +
    `*Generated by FreightFlow AI (Mock Provider — Development Mode)*`;
}

export const providerName = 'mock';
